import { atom } from 'jotai';

export const countries = [
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BR', name: 'Brazil' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'CA', name: 'Canada' },
  { code: 'CL', name: 'Chile' },
  { code: 'CO', name: 'Colombia' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'EE', name: 'Estonia' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GR', name: 'Greece' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IN', name: 'India' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IT', name: 'Italy' },
  { code: 'JP', name: 'Japan' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MT', name: 'Malta' },
  { code: 'MX', name: 'Mexico' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NO', name: 'Norway' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'RO', name: 'Romania' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'ES', name: 'Spain' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'TH', name: 'Thailand' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
];

export const shopCategories = [
  { value: 'books', label: 'Books & Stationery' },
  { value: 'electronics', label: 'Electronics' },
  { value: 'fashion', label: 'Fashion' },
  { value: 'home', label: 'Home & Garden' },
  { value: 'beauty', label: 'Beauty & Personal Care' },
  { value: 'sports', label: 'Sports & Outdoors' },
  { value: 'toys', label: 'Toys & Games' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'baby', label: 'Baby Products' },
  { value: 'computers', label: 'Computers & Accessories' },
  { value: 'grocery', label: 'Grocery & Gourmet Food' },
  { value: 'health', label: 'Health & Household' },
  { value: 'industrial', label: 'Industrial & Scientific' },
  { value: 'luggage', label: 'Luggage & Travel Gear' },
  { value: 'movies', label: 'Movies & TV' },
  { value: 'music', label: 'Music, CDs & Vinyl' },
  { value: 'office', label: 'Office Products' },
  { value: 'pet', label: 'Pet Supplies' },
  { value: 'software', label: 'Software' },
  { value: 'tools', label: 'Tools & Home Improvement' },
  { value: 'video_games', label: 'Video Games' },
  { value: 'appliances', label: 'Appliances' },
  { value: 'arts', label: 'Arts, Crafts & Sewing' },
  { value: 'cell_phones', label: 'Cell Phones & Accessories' },
  { value: 'collectibles', label: 'Collectibles & Fine Art' },
  { value: 'gift_cards', label: 'Gift Cards' },
  { value: 'handmade', label: 'Handmade Products' },
  { value: 'jewelry', label: 'Jewelry' },
  { value: 'musical_instruments', label: 'Musical Instruments' },
  { value: 'prime_pantry', label: 'Prime Pantry' },
  { value: 'shoes', label: 'Shoes & Handbags' },
  { value: 'watches', label: 'Watches' },
  { value: 'garden', label: 'Patio, Lawn & Garden' },
  { value: 'medical', label: 'Medical Supplies & Equipment' },
  { value: 'services', label: 'Home Services' },
  { value: 'renewed', label: 'Amazon Renewed' },
  { value: 'outdoors', label: 'Outdoor Recreation' },
  { value: 'subscriptions', label: 'Subscribe & Save' },
  { value: 'alcohol', label: 'Beer, Wine & Spirits' },
  { value: 'magazines', label: 'Magazine Subscriptions' },
  { value: 'lighting', label: 'Lighting & Ceiling Fans' },
  { value: 'security', label: 'Home Security & Surveillance' },
  { value: 'kitchen', label: 'Kitchen & Dining' },
  { value: 'bath', label: 'Bath' },
  { value: 'furniture', label: 'Furniture' },
  { value: 'crafts', label: 'Crafts & Hobbies' },
  { value: 'party', label: 'Party Supplies' },
  { value: 'costumes', label: 'Costumes & Accessories' },
  { value: 'personal_care', label: 'Personal Care Appliances' },
  { value: 'cleaning', label: 'Cleaning Supplies' },
  { value: 'storage', label: 'Storage & Organization' },
  { value: 'building_supplies', label: 'Building Supplies' },
  { value: 'hardware', label: 'Hardware' },
  { value: 'paint', label: 'Paint, Wall Treatments & Supplies' },
  { value: 'plumbing', label: 'Plumbing' },
  { value: 'electrical', label: 'Electrical' },
  { value: 'safety', label: 'Safety & Security' },
  { value: 'lab', label: 'Lab & Scientific Products' },
  { value: 'restaurant', label: 'Restaurant & Food Service' },
  { value: 'janitorial', label: 'Janitorial & Sanitation Supplies' },
  { value: 'education', label: 'Education Supplies' },
  { value: 'science', label: 'Science Education' },
  { value: 'diagnostic', label: 'Diagnostic & Screening' },
  { value: 'mobility', label: 'Mobility & Daily Living Aids' },
  { value: 'sexual_wellness', label: 'Sexual Wellness' },
  { value: 'erotic', label: 'Erotic Literature & Art' },
];

export const activeSidebarItem = atom<string>('/dashboard');

export const defaultColors = [
  '#000000',
  '#ffffff',
  '#ff0000',
  '#00ff00',
  '#0000ff',
  '#ffff00',
  '#ff00ff',
  '#00ffff',
];

export const aiEnhancements = [
  { label: 'Remove Background', effect: 'e-removedotbg' },
  { label: 'Drop Shadow', effect: 'e-dropshadow' },
  { label: 'Retouch', effect: 'e-retouch' },
  { label: 'Upscale', effect: 'e-upscale' },
  { label: 'Remove Blur', effect: 'e-removeblur' },
  { label: 'Remove Watermark', effect: 'e-removewatermark' },
];
